Nt pixel scale
B612-Asteroid-Institute/cutouts pull request #12
Opened 2023-01-23 23:55 UTC by ntellis

2023-01-25 02:28 UTC, ntellis commented
This PR changes the plotting functionality in Cutouts to read the pixel scale from the WCS (World coordinate system) values in the fits header of retrieved images, and use arcsecond rather than pixel values as the user input.

Note that our expectation is that a particular SIA service will provide fits images with the correct header info.

Also notably, NSC's SIA cutout service differs from SkyMapper's SIA cutout service in the format of the result table returned. This implies that a dataset-specific handler to coerce a particular SIA response to a common format will be required to have the core plotting utilities be general.

2023-02-13 16:46 UTC, akoumjian requested changes

2023-02-13 16:46 UTC, akoumjian commented on cutouts/io.py
> +    if isinstance(result, SIAResults):
What's going on here? Is it the `SIAService` class itself that returns different types depending on which server you query? If so, we can wrap that class to provide a consistent interface and put this conditional inside it?

2023-02-13 16:46 UTC, akoumjian commented on cutouts/plot.py
> +    pixel_scales = proj_plane_pixel_scales(wcs)
nitpick, but can we unpack these into something like `width_pixel_scale, height_pixel_scale` rather than using indexing?

2023-02-18 01:15 UTC, ntellis commented
Recent commits include the changes suggested by @akoumjian 

Additionally, crosshairs / arrow dimensions are now specified in arcseconds and scaled according to WCS. This seemed to make sense, given that now the entry point to Cutouts assumes no knowledge of the number of pixels returned per arcsecond for a given cutout provider. It also lets us use the crosshairs as a visual scale, as below (skymapper cutout of Edlu from 2014, 30"x30", and a sample from nsc, 20"x20"). Note the velocity vector in the NSC case is bogus.

![skymapper_edlu_30](https://user-images.githubusercontent.com/28658482/219823667-9470682e-7b12-412f-8801-ec3e3cfd010b.png)
![Screenshot 2023-02-17 at 5 12 31 PM](https://user-images.githubusercontent.com/28658482/219823676-73b434b3-d660-4324-b158-7520239b6f1d.png)

The other thought I had was to just scale the crosshairs/arrow proportionally to the image size, and happy to change over to that if that seems more intuitive.

2023-02-18 01:36 UTC, moeyensj commented
This is a great change!

2023-02-21 17:20 UTC, KatKiker commented
I have some reservations about changing the size of the arrow with the scale. Usually when one velocity vector is larger than another, it means the magnitude is greater. In the above images, for example, most people would read this as the top asteroid moving slower than the bottom, not that they had different arcsecond scales. 

I don't think it would matter as long as all the cutouts are the same arcsecond length though.

2023-02-21 17:24 UTC, ntellis commented
> I have some reservations about changing the size of the arrow with the scale. Usually when one velocity vector is larger than another, it means the magnitude is greater. In the above images, for example, most people would read this as the top asteroid moving slower than the bottom, not that they had different arcsecond scales.
> 
> I don't think it would matter as long as all the cutouts are the same arcsecond length though.

I'll adjust this so that the velocity vector is scaled to the image size instead of being specified in arcseconds. Your point is well taken that it seems to imply magnitude.

2023-03-01 20:47 UTC, ntellis commented on cutouts/sia.py
> +                result["access_url"] = result["get_fits"]
@akoumjian Specifically these conditionals were added to support the different fields we get back from the two SIA services.

2023-03-09 18:39 UTC, moeyensj commented
This was merged in #15. @ntellis are you okay if I close this?

2023-03-09 21:32 UTC, ntellis commented
A-OK

2023-03-09 21:32 UTC, closed without merging